---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-secrets-operator-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - apps.k8s.containerinfra.com
    resources:
      - generatedsecret
      - generatedsecret/status
    verbs:
      - update
      - delete
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-secrets-operator-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-secrets-operator-role
subjects:
  - kind: ServiceAccount
    name: kube-secrets-operator
    namespace: {{ .Release.Namespace }}
---
