---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeSecretsOperator.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.containerinfra.com
  resources:
  - generatedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.k8s.containerinfra.com
  resources:
  - generatedsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - apps.k8s.containerinfra.com
  resources:
  - generatedsecrets/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeSecretsOperator.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeSecretsOperator.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubeSecretsOperator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
