name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: make test
  
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Helm
        uses: azure/setup-helm@v4
      - name: Lint Helm charts
        run: |
          for chart in chart/*/; do
            if [ -f "${chart}Chart.yaml" ]; then
              echo "Linting chart: ${chart}"
              helm lint "${chart}"
            fi
          done
